### ISSUE TITLE
Keys should have their own syntax highlight color

### ISSUE THREAD

**Issue by tterrag1098** [de-jcup/eclipse-hijson-editor#1]
JSON is mostly strings, so I think JSON keys should be colored differently to string values, otherwise any JSON file is about ~90% one color.

Btw, cool to see a new JSON editor plugin!

**Comment by de-jcup** [comment]
Yes indeed, own color for keys would be nice. And I think it could be done without decreasing speed - maybe.

Just for clarification - in next example

``` json
{
    "key1" : "value1",
    
    "key2" : { 
    	"key3" : "value3",
    	"key4" : [ 
    	{ 
    		"key5" : "value5a"
    	},
    	{ 
    		"key5" : "value5b"
    	}
    	]
    }
}
```

you would like to have all of the keys rendered in own color.

**Comment by tterrag1098** [comment]
Yes, exactly.

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/109225153-306e6e80-77bd-11eb-99ce-6bf3a7edb706.png)

![image](https://user-images.githubusercontent.com/11644753/109225244-4e3bd380-77bd-11eb-84d3-598d56281f1a.png)

**Comment by de-jcup** [comment]
@tterrag1098 : I just deployed version 1.0.0 on eclipse marketplace containing the changes.
