### ISSUE TITLE
Any place in the UI to show the full-path (dot notation) of currently selected item

### ISSUE THREAD

**Issue by gurcei** [de-jcup/eclipse-hijson-editor#25]
Given:
```
{
  A: {
    B: {
      C: {
      }
    }
```
If I've selected C item in the editor, it'd be nice if there was some place within the UI to display the full dot-notation path `A.B.C`

**Comment by de-jcup** [comment]
Hm... at the yaml editor I implemented a similar feature: At the outline view toolbar there is a icon where you can copy the dot-notation path of the (inside outline) selected element:

![image](https://user-images.githubusercontent.com/11644753/190185266-679e0a2e-3a55-4239-93e2-76b0fa75708e.png)

The copied path in the picture above was : `a.b.c`.

If I would adopt it the same way for HiJson editor, would this fulfill your request as well?

**Comment by gurcei** [comment]
Yeah, I reckon it'll be sufficient for me, especially if you've already got the existing solution handy that you can port across and save you too much stress :-)

Just for the backstory on how it came on my radar, a colleague showed me how it looks in his vscode ide, a nice bar at the top of the editor that is always updated in realtime (I think they call it the breadcrumb bar there), and I inevitably got very jealous that eclipse didn't have something like this :-D

I guess having something similar for eclipse would be a tonne of work, so I'm happy for any modest, incremental update like you suggest that could get us the same info.

**Comment by de-jcup** [comment]
Sorry for answering so late - I will add the described feature into the HiJSON editor in next release. Maybe I will try to listen to line changes (cursor) and show the key inside the status line (bottom, like for line numbers , columns etc.). But I am not sure how difficult it will be to implement.

**Comment by de-jcup** [comment]
@gurcei : I have just released Version 1.3.0 on eclipse marketplace. It contains your wanted feature.

**Comment by de-jcup** [comment]
Video for the features is available at https://youtu.be/ljYvULscFGA

**Comment by gurcei** [comment]
Very nice, thank you! :)
