### ISSUE TITLE
Colors not adjusted to dark theme

### ISSUE THREAD

**Issue by SimonCockx** [de-jcup/eclipse-hijson-editor#27]
When I install this plugin and open a JSON file, I see the following. This isn't very readable.

![image](https://user-images.githubusercontent.com/47859223/202118351-0aac2c3e-164f-4b2e-90f7-bf65134ecd51.png)

I'm using Eclipse 2022-09.

**Comment by de-jcup** [comment]
Please look at https://github.com/de-jcup/eclipse-hijson-editor/wiki/FAQ#how-can-i-have-suitable-colours-in-dark-theme
