### ISSUE TITLE
Text does not fit with dark theme

### ISSUE THREAD

**Issue by NR67** [de-jcup/eclipse-hijson-editor#3]
Its very difficult to read text in dark theme. I would like that hijson work with dark theme because light theme burns my eyes.

**Comment by de-jcup** [comment]
Please just go to preferences, search for "hijson" and press at syntax color page the "Restore defaults for dark theme" button - or customize the button as you like.

![image](https://user-images.githubusercontent.com/11644753/102690404-7e875480-4205-11eb-852e-c73fbfb1250b.png)

When you have done this, the colors IMHO look okay. 

![image](https://user-images.githubusercontent.com/11644753/102690474-ed64ad80-4205-11eb-9036-e54535d9f029.png)

I also created a FAQ entry at https://github.com/de-jcup/eclipse-hijson-editor/wiki/FAQ#how-can-i-have-suitable-colours-in-dark-theme
